# Generated by Django 2.2.6 on 2019-10-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='options',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='url',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
