# Generated by Django 2.2.6 on 2019-10-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoCategory', models.CharField(max_length=50)),
                ('imageURL', models.CharField(max_length=255)),
            ],
        ),
    ]
