# Generated by Django 2.2.6 on 2019-10-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('categories', models.CharField(max_length=255)),
                ('videoId', models.CharField(max_length=50)),
                ('videoThumbnail', models.CharField(max_length=255)),
                ('videoFile', models.CharField(max_length=255)),
                ('likeRatio', models.IntegerField()),
                ('viewCount', models.IntegerField(default=0)),
                ('callCount', models.IntegerField(default=0)),
                ('funSticker', models.IntegerField(default=0)),
                ('notFunSticker', models.IntegerField(default=0)),
                ('updateDate', models.DateTimeField()),
            ],
        ),
    ]
