# Generated by Django 2.2.6 on 2019-10-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videoFile',
            field=models.CharField(max_length=1000),
        ),
    ]
